/*
Banco de dados relacionado a app de Java - VisitMap MVC

Lais Alves Da Silva Cruz - RM:552258 - Turma : 2TDSPH

------------------ ESSE SCRIPT CONTEM OS DDL E OS DEMAIS SOLICITADOS EM DEVOPS PARA DEPLOY NO AZURE PIPELINES ------------------
*/

/* DDL - Comandos para criar e estruturar as tabelas */

/* DROPS - Remove tabelas existentes para evitar conflitos */
DROP TABLE itinerary_place CASCADE CONSTRAINTS; -- Remove tabela de relacionamentos
DROP TABLE place CASCADE CONSTRAINTS; -- Remove tabela de lugares
DROP TABLE itinerary CASCADE CONSTRAINTS; -- Remove tabela de itinerários

/* DDL */

/* Tabela PLACE - Armazena informações sobre os lugares turísticos */
CREATE TABLE place (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Chave primária
    cidade VARCHAR2(255 CHAR) NOT NULL, -- Nome da cidade onde o lugar está localizado
    descricao VARCHAR2(255 CHAR) NOT NULL, -- Descrição do lugar
    entrada VARCHAR2(255 CHAR) CHECK (entrada IN ('PAGO', 'GRATUITO')), -- Tipo de entrada
    estado VARCHAR2(255 CHAR) NOT NULL, -- Estado onde o lugar está localizado
    nome VARCHAR2(255 CHAR) NOT NULL, -- Nome do lugar
    rua VARCHAR2(255 CHAR) NOT NULL, -- Nome da rua onde o lugar está localizado
    tipo VARCHAR2(255 CHAR) CHECK (tipo IN ('MUSEU', 'MONUMENTO', 'TEATRO', 'ESTATUA', 'PARQUE', 'OUTRO')), -- Tipo do lugar
    url_imagem VARCHAR2(255 CHAR) -- URL da imagem do lugar
);

/* Tabela ITINERARY - Armazena informações sobre itinerários */
CREATE TABLE itinerary (
    id NUMBER(19,0) GENERATED AS IDENTITY PRIMARY KEY, -- Chave primária
    data_criacao DATE, -- Data de criação do itinerário
    nome VARCHAR2(255 CHAR) NOT NULL, -- Nome do itinerário
    pais VARCHAR2(255 CHAR) CHECK (pais IN ('BRASIL', 'ARGENTINA', 'EUA', 'CANADA', 'FRANCA', 'ALEMANHA', 'ITALIA', 'ESPANHA', 'PORTUGAL', 'AUSTRALIA', 'JAPAO', 'CHINA', 'INDIA', 'MEXICO', 'AFRICA_DO_SUL', 'REINO_UNIDO')) -- País do itinerário
);

/* Tabela ITINERARY_PLACE - Tabela de relacionamentos entre itinerários e lugares */
CREATE TABLE itinerary_place (
    itinerary_id NUMBER(19,0) NOT NULL, -- ID do itinerário
    place_id NUMBER(19,0) NOT NULL, -- ID do lugar
    PRIMARY KEY (itinerary_id, place_id), -- Chave primária composta
    CONSTRAINT FK_itinerary FOREIGN KEY (itinerary_id) REFERENCES itinerary(id), -- Chave estrangeira referenciando itinerary
    CONSTRAINT FK_place FOREIGN KEY (place_id) REFERENCES place(id) -- Chave estrangeira referenciando place
);

/* INSERTS DE DADOS */

/* Inserir dados na tabela PLACE */
INSERT INTO place (nome, descricao, cidade, estado, rua, tipo, entrada, url_imagem) VALUES ('Cristo Redentor', 'Estátua icônica no Rio de Janeiro', 'Rio de Janeiro', 'RJ', 'Rua Cosme Velho', 'ESTATUA', 'PAGO', 'https://abrir.link/ZLXgi');
INSERT INTO place (nome, descricao, cidade, estado, rua, tipo, entrada, url_imagem) VALUES ('Museu do Ipiranga', 'Museu histórico localizado em São Paulo', 'São Paulo', 'SP', 'Parque da Independência', 'MUSEU', 'PAGO', 'https://abrir.link/rztKU');
INSERT INTO place (nome, descricao, cidade, estado, rua, tipo, entrada, url_imagem) VALUES ('Torre Eiffel', 'Famoso marco em Paris', 'Paris', 'Ile-de-France', 'Champ de Mars', 'MONUMENTO', 'PAGO', 'https://abrir.link/NdfEB');
INSERT INTO place (nome, descricao, cidade, estado, rua, tipo, entrada, url_imagem) VALUES ('Museu do Louvre', 'Museu de arte famoso em Paris', 'Paris', 'Ile-de-France', 'Rue de Rivoli', 'MUSEU', 'PAGO', 'https://abrir.link/fYLhP');

/* Inserir dados na tabela ITINERARY */
INSERT INTO itinerary (nome, pais, data_criacao) VALUES ('Exploração do Brasil', 'BRASIL', TO_DATE('2024-10-24', 'YYYY-MM-DD'));
INSERT INTO itinerary (nome, pais, data_criacao) VALUES ('Tour pela Europa', 'FRANCA', TO_DATE('2024-10-24', 'YYYY-MM-DD'));

/* Inserir dados na tabela ITINERARY_PLACE (relacionando itinerários e lugares) */
INSERT INTO itinerary_place (itinerary_id, place_id) VALUES (1, 1); -- Relaciona o primeiro itinerário ao Cristo Redentor
INSERT INTO itinerary_place (itinerary_id, place_id) VALUES (1, 2); -- Relaciona o primeiro itinerário ao Museu do Ipiranga
INSERT INTO itinerary_place (itinerary_id, place_id) VALUES (2, 3); -- Relaciona o segundo itinerário à Torre Eiffel
INSERT INTO itinerary_place (itinerary_id, place_id) VALUES (2, 4); -- Relaciona o segundo itinerário ao Museu do Louvre

/* Selecionar todos os registros das tabelas */

/* Selecionar todos os lugares cadastrados */
SELECT * FROM place;

/* Selecionar todos os itinerários cadastrados */
SELECT * FROM itinerary;

/* Selecionar todos os relacionamentos entre itinerários e lugares */
SELECT * FROM itinerary_place;
